workspace 'PTKit'

target :PTKit do
    platform :ios, '9.0'
    pod 'MBProgressHUD'
    pod 'EGOTableViewPullRefresh'
    pod 'Nimbus/Core'
    pod 'Nimbus/Models'
    pod 'Nimbus/Collections'
    pod 'Nimbus/AttributedLabel'
    pod 'CocoaLumberjack', '~> 2.0.0-beta4'
	pod 'libextobjc'
    pod 'SDWebImage/Core'
    pod 'WebViewJavascriptBridge'
    pod 'UICKeyChainStore'
    pod 'ZBarSDK', :path => 'LocalCocoaPod/ZBar'
    pod 'ZXing'
    pod 'libqrencode'
    pod 'libextobjc'
    pod 'MWPhotoBrowser'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'Masonry'
    pod 'GPUImage'
    pod 'JSONKit-NoWarning'
    pod 'Aspects'
	pod 'JRSwizzle'
	pod 'JSONKit-NoWarning'
	pod 'UICKeyChainStore'
	pod 'GBDeviceInfo'
end
