workspace 'PTKit'

target :PTKit do
    platform :ios, '6.1'
    pod 'MBProgressHUD'
    pod 'EGOTableViewPullRefresh'
    pod 'Nimbus/Core'
    pod 'Nimbus/Models'
    pod 'Nimbus/Collections'
    pod 'Nimbus/AttributedLabel'
    pod 'CocoaLumberjack', '~> 2.0.0-beta4'
	pod 'libextobjc'
    pod 'SDWebImage/Core'
    pod 'SDWebImage/WebP'
    pod 'WebViewJavascriptBridge'
    pod 'UICKeyChainStore'
    pod 'ZBarSDK', :path => 'LocalCocoaPod/ZBar'
    pod 'ZXing'
    pod 'libqrencode'
    pod 'libextobjc'
    pod 'MWPhotoBrowser'
    pod 'AFNetworking'
end