#import <Foundation/Foundation.h>

//HomePageModuleConstant.java
#define CC_HOMEPAGEMODULECONSTANT_USERCOLLECT @"USERCOLLECT"
#define CC_HOMEPAGEMODULECONSTANT_CATEGORY @"CATEGORY"
#define CC_HOMEPAGEMODULECONSTANT_TYPE0 @"TYPE0"
#define CC_HOMEPAGEMODULECONSTANT_TYPE1 @"TYPE1"
#define CC_HOMEPAGEMODULECONSTANT_TYPE2 @"TYPE2"
#define CC_HOMEPAGEMODULECONSTANT_TYPE3 @"TYPE3"
#define CC_HOMEPAGEMODULECONSTANT_TYPE4 @"TYPE4"
#define CC_HOMEPAGEMODULECONSTANT_TYPE5 @"TYPE5"
#define CC_HOMEPAGEMODULECONSTANT_TYPE6 @"TYPE6"
#define CC_HOMEPAGEMODULECONSTANT_TYPE7 @"TYPE7"
#define CC_HOMEPAGEMODULECONSTANT_TYPE8 @"TYPE8"
#define CC_HOMEPAGEMODULECONSTANT_TYPE9 @"TYPE9"
#define CC_HOMEPAGEMODULECONSTANT_TYPE10 @"TYPE10"
#define CC_HOMEPAGEMODULECONSTANT_TYPE11 @"TYPE11"
#define CC_HOMEPAGEMODULECONSTANT_TYPE12 @"TYPE12"


