#import <Foundation/Foundation.h>

//HomePageModuleConstant.java
#define CC_HOMEPAGEMODULECONSTANT_USERCOLLECT @"USERCOLLECT"
#define CC_HOMEPAGEMODULECONSTANT_CATEGORY @"CATEGORY"
#define CC_HOMEPAGEMODULECONSTANT_TYPE0 @"TYPE0"
#define CC_HOMEPAGEMODULECONSTANT_TYPE1 @"TYPE1"
#define CC_HOMEPAGEMODULECONSTANT_TYPE2 @"TYPE2"
#define CC_HOMEPAGEMODULECONSTANT_TYPE3 @"TYPE3"
#define CC_HOMEPAGEMODULECONSTANT_TYPE4 @"TYPE4"
#define CC_HOMEPAGEMODULECONSTANT_TYPE5 @"TYPE5"
#define CC_HOMEPAGEMODULECONSTANT_TYPE6 @"TYPE6"
#define CC_HOMEPAGEMODULECONSTANT_TYPE7 @"TYPE7"
#define CC_HOMEPAGEMODULECONSTANT_TYPE8 @"TYPE8"
#define CC_HOMEPAGEMODULECONSTANT_TYPE9 @"TYPE9"
#define CC_HOMEPAGEMODULECONSTANT_TYPE10 @"TYPE10"
#define CC_HOMEPAGEMODULECONSTANT_TYPE11 @"TYPE11"
#define CC_HOMEPAGEMODULECONSTANT_TYPE12 @"TYPE12"
#define CC_HOMEPAGEMODULECONSTANT_TYPE13 @"TYPE13"
#define CC_HOMEPAGEMODULECONSTANT_TYPE14 @"TYPE14"
#define CC_HOMEPAGEMODULECONSTANT_TYPE15 @"TYPE15"

/**
 *  以下是1.6新增大积木类型
 */
#define CC_HOMEPAGEMODULECONSTANT_TYPE16 @"TYPE16"
#define CC_HOMEPAGEMODULECONSTANT_TYPE17 @"TYPE17"
#define CC_HOMEPAGEMODULECONSTANT_CHEAPEST @"CHEAPEST"
#define CC_HOMEPAGEMODULECONSTANT_SELL_WELL @"SELL_WELL"
#define CC_HOMEPAGEMODULECONSTANT_EXPAND_ALL_CATEGORY @"EXPAND_ALL_CATEGORY"

/**
 *  1.7新增积木
 */
#define CC_HOMEPAGEMODULECONSTANT_DM @"DM"


