//
//  HttpRequestConstants.h
//  PTKit
//
//  Created by LeeHu on 6/20/16.
//  Copyright © 2016 LeeHu. All rights reserved.
//

#ifndef HttpRequestConstants_h
#define HttpRequestConstants_h

#define HTTPREQUESTCONSTANTS_KEY_UID @"u"
#define HTTPREQUESTCONSTANTS_KEY_SESSION @"s"
#define HTTPREQUESTCONSTANTS_KEY_VERSION @"v"
#define HTTPREQUESTCONSTANTS_KEY_DEVICE_TYPE @"t"
#define HTTPREQUESTCONSTANTS_KEY_MODE @"m"
#define HTTPREQUESTCONSTANTS_KEY_USER_AGENT @"a"
#define HTTPREQUESTCONSTANTS_KEY_NETWORK_TYPE @"n"
#define HTTPREQUESTCONSTANTS_KEY_SIGN_TOKEN @"o"


#define HTTPREQUESTCONSTANTS_HTTP_CODE_OK 200
#define HTTPREQUESTCONSTANTS_HTTP_CODE_NOT_MODIFIED 304
#define HTTPREQUESTCONSTANTS_HTTP_CODE_DIFF_PATCH 281
#define HTTPREQUESTCONSTANTS_HTTP_CODE_DECRYPT_FAIL 496
#define HTTPREQUESTCONSTANTS_ZIP_MIN_SIZE 100


#endif /* HttpRequestConstants_h */
