//
//  IReturnCode.h
//  PTKit
//
//  Created by LeeHu on 6/21/16.
//  Copyright © 2016 LeeHu. All rights reserved.
//

#ifndef IReturnCode_h
#define IReturnCode_h


#define IRETURNCODE_OK 0
#define IRETURNCODE_RPC_INVALID_PARAM -1
#define IRETURNCODE_BUS_INVALID_PARAM -2
#define IRETURNCODE_SESSION_TIMEOUTED -3
#define IRETURNCODE_DATABASE_ERROR -4
#define IRETURNCODE_USER_NOT_EXISTED -5
#define IRETURNCODE_PERMISSION_DENIED -6
#define IRETURNCODE_UPLOAD_FAILED -7
#define IRETURNCODE_FORCED_UPGRADED -8
#define IRETURNCODE_VERSION_UNMATCHED -9
#define IRETURNCODE_EXCEED_LIMIT -10
#define IRETURNCODE_BLOCKED_DEVICEID -11
#define IRETURNCODE_BLOCKED_USERID -12
#define IRETURNCODE_UNKOWN -13
#define IRETURNCODE_BAD_FORMAT -14
#define IRETURNCODE_NETWORK_TIMEOUT -15
#define IRETURNCODE_USER_CHANGED -16
#define IRETURNCODE_TOO_FREQUENT -17
#define IRETURNCODE_ACTION_FAILED -18
#define IRETURNCODE_REQUEST_FILTERED -19
#define IRETURNCODE_ASYNC_CALL_TIMEOUT -20
#define IRETURNCODE_ASYNC_CALL_ERROR -21
#define IRETURNCODE_SESSION_CLEARED -22

#endif /* IReturnCode_h */
